// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKbUfp53uNjX6vZ3TqRlvx_QpCxLI7uaA',
    appId: '1:85190985458:web:bd2807eded3d8cc167b26b',
    messagingSenderId: '85190985458',
    projectId: 'fir-macdonalds',
    authDomain: 'fir-macdonalds.firebaseapp.com',
    storageBucket: 'fir-macdonalds.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB50ACl8O4HEY9od_DXbZ6Jfe9GynRd7N0',
    appId: '1:85190985458:android:ee8958b9cb56538a67b26b',
    messagingSenderId: '85190985458',
    projectId: 'fir-macdonalds',
    storageBucket: 'fir-macdonalds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW7NflTBtkw46l4ujImAFIqyrw6i58iws',
    appId: '1:85190985458:ios:8fd0c46bfa5c83b467b26b',
    messagingSenderId: '85190985458',
    projectId: 'fir-macdonalds',
    storageBucket: 'fir-macdonalds.firebasestorage.app',
    iosBundleId: 'com.example.mcDonalds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW7NflTBtkw46l4ujImAFIqyrw6i58iws',
    appId: '1:85190985458:ios:8fd0c46bfa5c83b467b26b',
    messagingSenderId: '85190985458',
    projectId: 'fir-macdonalds',
    storageBucket: 'fir-macdonalds.firebasestorage.app',
    iosBundleId: 'com.example.mcDonalds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKbUfp53uNjX6vZ3TqRlvx_QpCxLI7uaA',
    appId: '1:85190985458:web:c5e6293abcbfcebc67b26b',
    messagingSenderId: '85190985458',
    projectId: 'fir-macdonalds',
    authDomain: 'fir-macdonalds.firebaseapp.com',
    storageBucket: 'fir-macdonalds.firebasestorage.app',
  );
}
